[project]
name = 'Decentralized-Marketing-Campaign-Performance-Analytics'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.analysis-automation]
path = 'contracts/analysis-automation.clar'
clarity_version = 2
epoch = 2.5

[contracts.analytics-provider-verification]
path = 'contracts/analytics-provider-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
